// Generated by Smart Mockup Creator - Performance Test
// Date: 2025-09-01 19:42:12 +0000
// Mockups: 50, Layers per mockup: 5

#include "Batch Mockup Smart Object Replacement.jsx"

var outputOpts = {
  path: '$/_output',
  format: 'jpg',
  zeroPadding: true,
  filename: '@input_@mockup'
};

mockups([
  {
    output: outputOpts,
    mockupPath: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/mockup-large/mockup_1.psd',
    smartObjects: [
      {
        target: 'smart_object_1',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_2',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_3',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_4',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_5',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      }
    ]
  },

  {
    output: outputOpts,
    mockupPath: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/mockup-large/mockup_2.psd',
    smartObjects: [
      {
        target: 'smart_object_1',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_2',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_3',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_4',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_5',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      }
    ]
  },

  {
    output: outputOpts,
    mockupPath: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/mockup-large/mockup_3.psd',
    smartObjects: [
      {
        target: 'smart_object_1',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_2',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_3',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_4',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_5',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      }
    ]
  },

  {
    output: outputOpts,
    mockupPath: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/mockup-large/mockup_4.psd',
    smartObjects: [
      {
        target: 'smart_object_1',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_2',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_3',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_4',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_5',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      }
    ]
  },

  {
    output: outputOpts,
    mockupPath: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/mockup-large/mockup_5.psd',
    smartObjects: [
      {
        target: 'smart_object_1',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_2',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_3',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_4',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_5',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      }
    ]
  },

  {
    output: outputOpts,
    mockupPath: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/mockup-large/mockup_6.psd',
    smartObjects: [
      {
        target: 'smart_object_1',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_2',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_3',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_4',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_5',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      }
    ]
  },

  {
    output: outputOpts,
    mockupPath: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/mockup-large/mockup_7.psd',
    smartObjects: [
      {
        target: 'smart_object_1',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_2',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_3',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_4',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_5',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      }
    ]
  },

  {
    output: outputOpts,
    mockupPath: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/mockup-large/mockup_8.psd',
    smartObjects: [
      {
        target: 'smart_object_1',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_2',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_3',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_4',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_5',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      }
    ]
  },

  {
    output: outputOpts,
    mockupPath: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/mockup-large/mockup_9.psd',
    smartObjects: [
      {
        target: 'smart_object_1',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_2',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_3',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_4',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_5',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      }
    ]
  },

  {
    output: outputOpts,
    mockupPath: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/mockup-large/mockup_10.psd',
    smartObjects: [
      {
        target: 'smart_object_1',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_2',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_3',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_4',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_5',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      }
    ]
  },

  {
    output: outputOpts,
    mockupPath: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/mockup-large/mockup_11.psd',
    smartObjects: [
      {
        target: 'smart_object_1',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_2',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_3',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_4',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_5',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      }
    ]
  },

  {
    output: outputOpts,
    mockupPath: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/mockup-large/mockup_12.psd',
    smartObjects: [
      {
        target: 'smart_object_1',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_2',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_3',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_4',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_5',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      }
    ]
  },

  {
    output: outputOpts,
    mockupPath: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/mockup-large/mockup_13.psd',
    smartObjects: [
      {
        target: 'smart_object_1',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_2',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_3',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_4',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_5',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      }
    ]
  },

  {
    output: outputOpts,
    mockupPath: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/mockup-large/mockup_14.psd',
    smartObjects: [
      {
        target: 'smart_object_1',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_2',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_3',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_4',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_5',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      }
    ]
  },

  {
    output: outputOpts,
    mockupPath: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/mockup-large/mockup_15.psd',
    smartObjects: [
      {
        target: 'smart_object_1',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_2',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_3',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_4',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_5',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      }
    ]
  },

  {
    output: outputOpts,
    mockupPath: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/mockup-large/mockup_16.psd',
    smartObjects: [
      {
        target: 'smart_object_1',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_2',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_3',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_4',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_5',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      }
    ]
  },

  {
    output: outputOpts,
    mockupPath: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/mockup-large/mockup_17.psd',
    smartObjects: [
      {
        target: 'smart_object_1',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_2',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_3',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_4',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_5',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      }
    ]
  },

  {
    output: outputOpts,
    mockupPath: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/mockup-large/mockup_18.psd',
    smartObjects: [
      {
        target: 'smart_object_1',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_2',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_3',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_4',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_5',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      }
    ]
  },

  {
    output: outputOpts,
    mockupPath: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/mockup-large/mockup_19.psd',
    smartObjects: [
      {
        target: 'smart_object_1',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_2',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_3',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_4',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_5',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      }
    ]
  },

  {
    output: outputOpts,
    mockupPath: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/mockup-large/mockup_20.psd',
    smartObjects: [
      {
        target: 'smart_object_1',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_2',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_3',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_4',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_5',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      }
    ]
  },

  {
    output: outputOpts,
    mockupPath: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/mockup-large/mockup_21.psd',
    smartObjects: [
      {
        target: 'smart_object_1',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_2',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_3',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_4',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_5',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      }
    ]
  },

  {
    output: outputOpts,
    mockupPath: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/mockup-large/mockup_22.psd',
    smartObjects: [
      {
        target: 'smart_object_1',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_2',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_3',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_4',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_5',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      }
    ]
  },

  {
    output: outputOpts,
    mockupPath: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/mockup-large/mockup_23.psd',
    smartObjects: [
      {
        target: 'smart_object_1',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_2',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_3',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_4',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_5',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      }
    ]
  },

  {
    output: outputOpts,
    mockupPath: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/mockup-large/mockup_24.psd',
    smartObjects: [
      {
        target: 'smart_object_1',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_2',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_3',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_4',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_5',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      }
    ]
  },

  {
    output: outputOpts,
    mockupPath: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/mockup-large/mockup_25.psd',
    smartObjects: [
      {
        target: 'smart_object_1',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_2',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_3',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_4',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_5',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      }
    ]
  },

  {
    output: outputOpts,
    mockupPath: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/mockup-large/mockup_26.psd',
    smartObjects: [
      {
        target: 'smart_object_1',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_2',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_3',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_4',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_5',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      }
    ]
  },

  {
    output: outputOpts,
    mockupPath: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/mockup-large/mockup_27.psd',
    smartObjects: [
      {
        target: 'smart_object_1',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_2',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_3',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_4',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_5',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      }
    ]
  },

  {
    output: outputOpts,
    mockupPath: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/mockup-large/mockup_28.psd',
    smartObjects: [
      {
        target: 'smart_object_1',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_2',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_3',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_4',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_5',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      }
    ]
  },

  {
    output: outputOpts,
    mockupPath: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/mockup-large/mockup_29.psd',
    smartObjects: [
      {
        target: 'smart_object_1',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_2',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_3',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_4',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_5',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      }
    ]
  },

  {
    output: outputOpts,
    mockupPath: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/mockup-large/mockup_30.psd',
    smartObjects: [
      {
        target: 'smart_object_1',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_2',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_3',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_4',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_5',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      }
    ]
  },

  {
    output: outputOpts,
    mockupPath: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/mockup-large/mockup_31.psd',
    smartObjects: [
      {
        target: 'smart_object_1',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_2',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_3',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_4',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_5',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      }
    ]
  },

  {
    output: outputOpts,
    mockupPath: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/mockup-large/mockup_32.psd',
    smartObjects: [
      {
        target: 'smart_object_1',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_2',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_3',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_4',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_5',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      }
    ]
  },

  {
    output: outputOpts,
    mockupPath: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/mockup-large/mockup_33.psd',
    smartObjects: [
      {
        target: 'smart_object_1',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_2',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_3',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_4',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_5',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      }
    ]
  },

  {
    output: outputOpts,
    mockupPath: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/mockup-large/mockup_34.psd',
    smartObjects: [
      {
        target: 'smart_object_1',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_2',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_3',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_4',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_5',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      }
    ]
  },

  {
    output: outputOpts,
    mockupPath: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/mockup-large/mockup_35.psd',
    smartObjects: [
      {
        target: 'smart_object_1',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_2',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_3',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_4',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_5',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      }
    ]
  },

  {
    output: outputOpts,
    mockupPath: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/mockup-large/mockup_36.psd',
    smartObjects: [
      {
        target: 'smart_object_1',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_2',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_3',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_4',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_5',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      }
    ]
  },

  {
    output: outputOpts,
    mockupPath: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/mockup-large/mockup_37.psd',
    smartObjects: [
      {
        target: 'smart_object_1',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_2',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_3',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_4',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_5',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      }
    ]
  },

  {
    output: outputOpts,
    mockupPath: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/mockup-large/mockup_38.psd',
    smartObjects: [
      {
        target: 'smart_object_1',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_2',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_3',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_4',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_5',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      }
    ]
  },

  {
    output: outputOpts,
    mockupPath: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/mockup-large/mockup_39.psd',
    smartObjects: [
      {
        target: 'smart_object_1',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_2',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_3',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_4',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_5',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      }
    ]
  },

  {
    output: outputOpts,
    mockupPath: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/mockup-large/mockup_40.psd',
    smartObjects: [
      {
        target: 'smart_object_1',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_2',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_3',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_4',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_5',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      }
    ]
  },

  {
    output: outputOpts,
    mockupPath: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/mockup-large/mockup_41.psd',
    smartObjects: [
      {
        target: 'smart_object_1',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_2',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_3',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_4',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_5',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      }
    ]
  },

  {
    output: outputOpts,
    mockupPath: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/mockup-large/mockup_42.psd',
    smartObjects: [
      {
        target: 'smart_object_1',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_2',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_3',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_4',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_5',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      }
    ]
  },

  {
    output: outputOpts,
    mockupPath: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/mockup-large/mockup_43.psd',
    smartObjects: [
      {
        target: 'smart_object_1',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_2',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_3',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_4',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_5',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      }
    ]
  },

  {
    output: outputOpts,
    mockupPath: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/mockup-large/mockup_44.psd',
    smartObjects: [
      {
        target: 'smart_object_1',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_2',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_3',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_4',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_5',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      }
    ]
  },

  {
    output: outputOpts,
    mockupPath: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/mockup-large/mockup_45.psd',
    smartObjects: [
      {
        target: 'smart_object_1',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_2',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_3',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_4',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_5',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      }
    ]
  },

  {
    output: outputOpts,
    mockupPath: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/mockup-large/mockup_46.psd',
    smartObjects: [
      {
        target: 'smart_object_1',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_2',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_3',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_4',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_5',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      }
    ]
  },

  {
    output: outputOpts,
    mockupPath: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/mockup-large/mockup_47.psd',
    smartObjects: [
      {
        target: 'smart_object_1',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_2',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_3',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_4',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_5',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      }
    ]
  },

  {
    output: outputOpts,
    mockupPath: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/mockup-large/mockup_48.psd',
    smartObjects: [
      {
        target: 'smart_object_1',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_2',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_3',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_4',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_5',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      }
    ]
  },

  {
    output: outputOpts,
    mockupPath: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/mockup-large/mockup_49.psd',
    smartObjects: [
      {
        target: 'smart_object_1',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_2',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_3',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_4',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_5',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      }
    ]
  },

  {
    output: outputOpts,
    mockupPath: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/mockup-large/mockup_50.psd',
    smartObjects: [
      {
        target: 'smart_object_1',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_2',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_3',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_4',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart_object_5',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/performance-test/input-large',
        align: 'center center',
        resize: 'fill'
      }
    ]
  }
]);

// Script completed successfully
// Total configurations: 250