// Generated by Smart Mockup Creator
// Date: 2025-09-01 19:39:13 +0000

#include "Batch Mockup Smart Object Replacement.jsx"

var outputOpts = {
  path: '$/_output',
  format: 'jpg',
  zeroPadding: true,
  filename: '@input_@mockup'
};

mockups([
  {
    output: outputOpts,
    mockupPath: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/mockup-files/mockup1.psd',
    smartObjects: [
      {
        target: 'smart object 1',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/input-files',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart object 2',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/input-files',
        align: 'left top',
        resize: 'fit'
      }
    ]
  },

  {
    output: outputOpts,
    mockupPath: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/mockup-files/mockup2.psd',
    smartObjects: [
      {
        target: 'smart object 1',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/input-files',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart object 2',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/input-files',
        align: 'left top',
        resize: 'fit'
      }
    ]
  },

  {
    output: outputOpts,
    mockupPath: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/mockup-files/mockup3.psb',
    smartObjects: [
      {
        target: 'smart object 1',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/input-files',
        align: 'center center',
        resize: 'fill'
      },
      {
        target: 'smart object 2',
        input: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/input-files',
        align: 'left top',
        resize: 'fit'
      }
    ]
  }
]);

// Script completed successfully