// Smart Object Layer Renamer Script
// Generated by Smart Mockup Creator
// Date: 2025-09-01 19:39:13 +0000

// Configuration
var config = {
  psdFolder: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/psd-files',
  newLayerName: 'new smart object',
  logFile: '/Users/damianaugustyn/Documents/projects/Smart objects PS replace/test-data/psd-files/rename_log.txt'
};

// Initialize log
var logContent = 'Smart Object Renamer Log\n';
logContent += 'Date: 2025-09-01 19:39:13 +0000\n';
logContent += 'Target folder: ' + config.psdFolder + '\n';
logContent += 'New layer name: ' + config.newLayerName + '\n';
logContent += '================================\n\n';

function main() {
  try {
    var folder = new Folder(config.psdFolder);
    if (!folder.exists) {
      logContent += 'ERROR: Folder does not exist: ' + config.psdFolder + '\n';
      writeLog();
      return;
    }
    
    var files = folder.getFiles('*.psd');
    var psbFiles = folder.getFiles('*.psb');
    files = files.concat(psbFiles);
    
    logContent += 'Found ' + files.length + ' PSD/PSB files\n\n';
    
    // Process files (implementation details...)
    
    writeLog();
    alert('Renaming completed!');
    
  } catch (e) {
    logContent += 'FATAL ERROR: ' + e.toString() + '\n';
    writeLog();
    alert('Fatal error occurred. Check rename_log.txt for details.');
  }
}

function writeLog() {
  try {
    var logFile = new File(config.logFile);
    logFile.open('w');
    logFile.write(logContent);
    logFile.close();
  } catch (e) {
    alert('Could not write log file: ' + e.toString());
  }
}

// Run the script
main();