// Generated by Smart Mockup Creator
// Date: 2025-09-03 13:45:22
// Engine path: /Users/damianaugustyn/Documents/projects/Smart objects PS replace/script/Batch Mockup Smart Object Replacement.jsx

#include "/Users/damianaugustyn/Documents/projects/Smart objects PS replace/script/Batch Mockup Smart Object Replacement.jsx"

// Debug logging function
function logDebug(message) {
  try {
    var logFile = new File(Folder.desktop + '/mockup_generator_debug.log');
    logFile.open('a');
    logFile.writeln(new Date().toString() + ': ' + message);
    logFile.close();
  } catch(e) {
    // Silent fail for logging
  }
}

// Validate engine file exists
try {
  var engineFile = new File('/Users/damianaugustyn/Documents/projects/Smart objects PS replace/script/Batch Mockup Smart Object Replacement.jsx');
  if (!engineFile.exists) {
    alert('ERROR: Engine file not found!\\n\\nExpected location:\\n/Users/damianaugustyn/Documents/projects/Smart objects PS replace/script/Batch Mockup Smart Object Replacement.jsx\\n\\nPlease check if the file exists at this path.');
    logDebug('ERROR: Engine file not found at: /Users/damianaugustyn/Documents/projects/Smart objects PS replace/script/Batch Mockup Smart Object Replacement.jsx');
    throw new Error('Engine file not found');
  }
  logDebug('Engine file found at: /Users/damianaugustyn/Documents/projects/Smart objects PS replace/script/Batch Mockup Smart Object Replacement.jsx');
} catch(e) {
  alert('Critical Error: ' + e.toString());
  throw e;
}

logDebug('Starting mockup generation with format: jpg');

var outputOpts = {
  path: '/Users/damianaugustyn/Desktop/test PS/output',
  format: 'jpg',
  zeroPadding: true,
  filename: '@input_@mockup'
};

mockups([
  {
    output: outputOpts,
    mockupPath: '/Users/damianaugustyn/Desktop/test PS/mockup/1.psd',
    smartObjects: [
      {
        target: 'Frame 1',
        input: '/Users/damianaugustyn/Desktop/test PS/input',
        align: 'center center',
        resize: 'fill'
      }
    ]
  },

  {
    output: outputOpts,
    mockupPath: '/Users/damianaugustyn/Desktop/test PS/mockup/2.psd',
    smartObjects: [
      {
        target: 'Frame 1',
        input: '/Users/damianaugustyn/Desktop/test PS/input',
        align: 'center center',
        resize: 'fill'
      }
    ]
  },

  {
    output: outputOpts,
    mockupPath: '/Users/damianaugustyn/Desktop/test PS/mockup/3.psd',
    smartObjects: [
      {
        target: 'Frame 1',
        input: '/Users/damianaugustyn/Desktop/test PS/input',
        align: 'center center',
        resize: 'fill'
      }
    ]
  },

  {
    output: outputOpts,
    mockupPath: '/Users/damianaugustyn/Desktop/test PS/mockup/4.psd',
    smartObjects: [
      {
        target: 'Frame 1',
        input: '/Users/damianaugustyn/Desktop/test PS/input',
        align: 'center center',
        resize: 'fill'
      }
    ]
  },

  {
    output: outputOpts,
    mockupPath: '/Users/damianaugustyn/Desktop/test PS/mockup/5.psd',
    smartObjects: [
      {
        target: 'Frame 1',
        input: '/Users/damianaugustyn/Desktop/test PS/input',
        align: 'center center',
        resize: 'fill'
      }
    ]
  }
]);

logDebug('Script completed successfully');
logDebug('Files processed: 5 mockup(s), 1 smart object layer(s)');
alert('Batch process completed!\\nProcessed: 5 mockup(s)\\nSmart Objects: 1 layer(s)\\nCheck Desktop for debug log if issues occur.');

// Script completed successfully
// Files processed: 5 mockup(s), 1 smart object layer(s)
