// Generated by Smart Mockup Creator
// Date: 2025-09-03 00:37:00
// Note: Make sure "Batch Mockup Smart Object Replacement.jsx" is in the same folder as this script

#include "Batch Mockup Smart Object Replacement.jsx"

// Debug logging function
function logDebug(message) {
  try {
    var logFile = new File(Folder.desktop + '/mockup_generator_debug.log');
    logFile.open('a');
    logFile.writeln(new Date().toString() + ': ' + message);
    logFile.close();
  } catch(e) {
    // Silent fail for logging
  }
}

// Validate engine file exists
try {
  var engineFile = new File($.fileName.replace(/[^/\\]*$/, '') + 'Batch Mockup Smart Object Replacement.jsx');
  if (!engineFile.exists) {
    alert('ERROR: Engine file not found!\n\nPlease ensure "Batch Mockup Smart Object Replacement.jsx" is in the same folder as this script.\n\nEngine file should be at:\n' + engineFile.fullName);
    logDebug('ERROR: Engine file not found at: ' + engineFile.fullName);
    throw new Error('Engine file not found');
  }
  logDebug('Engine file found at: ' + engineFile.fullName);
} catch(e) {
  alert('Critical Error: ' + e.toString());
  throw e;
}

logDebug('Starting mockup generation with format: jpg');

var outputOpts = {
  path: '/Users/damianaugustyn/Desktop/test PS/output',
  format: 'jpg',
  zeroPadding: true,
  filename: '@input_@mockup'
};

mockups([
  {
    output: outputOpts,
    mockupPath: '/Users/damianaugustyn/Desktop/test PS/mockup/1.psd',
    smartObjects: [
      {
        target: 'Frame 1',
        input: '/Users/damianaugustyn/Desktop/test PS/input',
        align: 'center center',
        resize: 'fill'
      }
    ]
  },

  {
    output: outputOpts,
    mockupPath: '/Users/damianaugustyn/Desktop/test PS/mockup/2.psd',
    smartObjects: [
      {
        target: 'Frame 1',
        input: '/Users/damianaugustyn/Desktop/test PS/input',
        align: 'center center',
        resize: 'fill'
      }
    ]
  },

  {
    output: outputOpts,
    mockupPath: '/Users/damianaugustyn/Desktop/test PS/mockup/3.psd',
    smartObjects: [
      {
        target: 'Frame 1',
        input: '/Users/damianaugustyn/Desktop/test PS/input',
        align: 'center center',
        resize: 'fill'
      }
    ]
  },

  {
    output: outputOpts,
    mockupPath: '/Users/damianaugustyn/Desktop/test PS/mockup/4.psd',
    smartObjects: [
      {
        target: 'Frame 1',
        input: '/Users/damianaugustyn/Desktop/test PS/input',
        align: 'center center',
        resize: 'fill'
      }
    ]
  },

  {
    output: outputOpts,
    mockupPath: '/Users/damianaugustyn/Desktop/test PS/mockup/5.psd',
    smartObjects: [
      {
        target: 'Frame 1',
        input: '/Users/damianaugustyn/Desktop/test PS/input',
        align: 'center center',
        resize: 'fill'
      }
    ]
  }
]);

logDebug('Script completed successfully');
logDebug('Files processed: 5 mockup(s), 1 smart object layer(s)');
alert('Batch process completed!\nProcessed: 5 mockup(s)\nSmart Objects: 1 layer(s)\nCheck Desktop for debug log if issues occur.');

// Script completed successfully
// Files processed: 5 mockup(s), 1 smart object layer(s)